# Generated by Django 3.0.3 on 2020-03-06 17:56

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='defaultName', max_length=200)),
                ('user_id', models.CharField(default='defaultUser', max_length=100)),
                ('pic_id', models.CharField(default='default_id', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='metadata',
            fields=[
                ('user_id', models.CharField(default='defaultUser', max_length=100)),
                ('rec_length', models.DurationField()),
                ('collection', models.CharField(default='defaultCollection', max_length=200)),
                ('tags', models.CharField(default='defaultTags', max_length=200)),
                ('category', models.CharField(default='defaultCategory', max_length=100)),
                ('title', models.CharField(default='defaultTitle', max_length=300)),
                ('fileID', models.CharField(default='defaultID', max_length=100, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('nonce', models.CharField(default='defaultNonce', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('inst_name', models.CharField(max_length=100)),
                ('inst_addr', models.CharField(max_length=100)),
                ('inst_city', models.CharField(max_length=100)),
                ('inst_state', models.CharField(max_length=100)),
                ('inst_country', models.CharField(max_length=100)),
                ('user_id', models.CharField(default='noID', max_length=100, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
