# Generated by Django 3.0.1 on 2020-01-20 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialektor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='instAddrOne',
            new_name='inst_addr',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='instAddrTwo',
            new_name='inst_city',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='instCity',
            new_name='inst_country',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='instCountry',
            new_name='inst_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='instName',
            new_name='inst_state',
        ),
    ]
