# Generated by Django 3.0.1 on 2020-01-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialektor', '0002_auto_20200120_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('rec_length', models.DurationField()),
                ('collection', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
