# Generated by Django 3.0.1 on 2020-02-10 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dialektor', '0004_auto_20200204_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='defaultName', max_length=200)),
                ('owner', models.CharField(default='defaultUser', max_length=100)),
                ('pic_id', models.CharField(default='defaultPic', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='metadata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadata',
            name='nonce',
            field=models.CharField(default='defaultNonce', max_length=100),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='user_id',
            field=models.CharField(default='defaultUser', max_length=100),
        ),
    ]
