# Generated by Django 3.0.3 on 2020-02-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialektor', '0006_auto_20200214_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='noID', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='pic_id',
            field=models.CharField(default='defaultPic', max_length=100, primary_key=True, serialize=False),
        ),
    ]
